#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""mkmodel -- SEED Core model creation script"""

from model import Model, DEFAULT_CORE_MODEL
from utils import _SEED_LOG, _init_logger

def main():
    """mkmodel program"""

    _init_logger()

    _SEED_LOG.info('creating core model ...')

    core = Model()

    core._gen_core()

    # Serialize the store as RDF/XML to file.
    core.serialize(DEFAULT_CORE_MODEL)

    _SEED_LOG.info("produced %d triples in %s." % (len(core), DEFAULT_CORE_MODEL))


if __name__ == '__main__':
    main()
