#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""mknode -- SEED node initialization"""

from uuid import uuid1 as _genid
from uuid import getnode as _getnode

from utils import _SEED_LOG, _init_logger, _version
from utils import DEFAULT_ROOT

from rdflib.graph import Graph
from rdflib.term import URIRef, Literal, BNode
from rdflib.namespace import Namespace, RDF, RDFS, OWL, XSD

def main():
    """mknode program"""

    _init_logger()

    _SEED_LOG.info('loading core model ...')

    model = Graph()
    model.load('seed.owl')

    _SEED_LOG.info('initializing node ...')

# fs_model.add(('root', 'version', _version()))
# fs_model.add(('root', 'is', 'bucket'))

# node = _getnode()
# objId = str(_genid(node = node))
# fs_model.add(('root', 'contain', objId))
# fs_model.add((objId, 'is', 'object'))
# fs_model.add((objId, 'name', 'test'))
# fs_model.add(('root', 'contain', 'test_bucket'))
# fs_model.add(('test_bucket', 'is', 'bucket'))

# fs_model.save('storage/test.csv')

if __name__ == '__main__':
    main()
