#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""mknode -- SEED node initialization"""

from uuid import uuid1 as _genid
from uuid import getnode as _getnode

from utils import _SEED_LOG, _init_logger, _version
from utils import DEFAULT_ROOT

from rdflib.graph import Graph
from rdflib.term import URIRef, Literal, BNode
from rdflib.namespace import Namespace, RDF, RDFS, OWL, XSD

def main():
    """mknode program"""

    _init_logger()

    _SEED_LOG.info('loading core model ...')

    model = Graph()
    model.load('seed.owl')

    _SEED_LOG.info('loaded %d triples.' % len(model))


    _SEED_LOG.info('initializing node ...')

    for s,p,o in model: 
        print s,p,o


if __name__ == '__main__':
    main()
