#!/usr/bin/env python
# -*- coding: UTF-8 -*-
"""
SEED -- A storage system based on 'Extemporal Ensemble' Devices
Aims at minimum deployment effort and dependencies, easy to manage and scale.
"""
#
#  Copyright 2012 Shi.Zhan
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

import sys

if float("%d.%d" %(sys.version_info[0], sys.version_info[1])) < 2.7:
    sys.stderr.write("WARNING: Python below 2.6 need argparse.\n")

import re, argparse

from shell import Shell
from server import Server
from model import DEFAULT_NODE_MODEL, init_model
from log import SEED_LOG, init_logger
from util import VERSION, WORKING_DIR
from netutil import DEFAULT_HOST

def main():
    """SEED main program"""

    init_logger()

    parser = argparse.ArgumentParser(
        description='Storage based on "Extemporal Ensemble" Devices'
        )

    parser.add_argument(
        '-v', '--version',
        action='version',
        version='%(prog)s ' + VERSION)

    parser.add_argument(
        '-s', '--server',
        action='store_true',
        dest='server',
        default=False,
        help='start server on specified ip and port',
        )

    parser.add_argument(
        '-c', '--cli',
        action='store_true',
        dest='cli',
        default=False,
        help='open command line interface on specified server'
        )

    parser.add_argument(
        '-a', '--address',
        action='store',
        dest='ip',
        default=DEFAULT_HOST,
        help='connect/create server on specified ip address',
        )

    parser.add_argument(
        '-p', '--port',
        action='store',
        dest='port',
        type=int,
        default=10001,
        help='connect/listen to specified port',
        )

    parser.add_argument(
        '-i', '--initialize',
        action='store_true',
        dest='initialize',
        default=False,
        help='initialize models'
        )

    parser.add_argument(
        '-d', '--dir',
        action='store',
        dest='root_dir',
        default=WORKING_DIR,
        help='specify root directory (use current directory as default) \
            for creating node model',
        )

    parser.add_argument(
        '-m', '--model',
        action='store',
        dest='model_file',
        default=DEFAULT_NODE_MODEL,
        help='load server on specified model file (default: node.owl)',
        )

    options = parser.parse_args()

    # valid ip, port
    valid_ip = \
        re.search(
            '^(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])(\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])){3}',
            options.ip
            )
    valid_port = (options.port > 1000 and options.port < 65535)

    if not (valid_ip and valid_port):
        print "invalid parameter, "\
              "should be as '-a 127.0.0.1 -p 10001 (between 1000 and 65535)'."

        exit(1)

    # which way to go ... start server or open cli or simply init then return?
    if options.initialize:
        # initialize models
        init_model(options.root_dir, options.model_file)

    elif options.cli:
        # run the shell @ host
        SEED_LOG.info('Opening command line interface on ip %s port %d ...' %
                       (options.ip, options.port))

        Shell(options.ip, options.port).cmdloop()

    elif options.server:
        # run the server on specified ip, port and root directory
        SEED_LOG.info('Serving on ip %s port %d with model file %s ...' %
                       (options.ip, options.port, options.model_file))

        Server(options.ip, options.port, options.model_file).run()

    else:
        print "either start server (-S) or enter CLI (-C), "\
              " or use -h to access help."


if __name__ == '__main__':
    main()
